#version: 3
#parallel_plan: true
#parallel_apply: true
#automerge: true
#delete_source_branch_on_merge: true
#projects:
#  - &template
#    name: template-project
#    dir: template-dir
#    workflow: terraform
#    workspace: default
#    apply_requirements: [mergeable]
#    delete_source_branch_on_merge: true
#    autoplan:
#      enabled: true
#      when_modified: ["*.tf", "*.tfvars"]
#
#  - <<: *template
#    name: ec2-nonprod
#    dir: ./envs/nonprod/
#    workspace: nonprod

#  - <<: *template
#    name: ec2-prod
#    dir: ./envs/prod/
#    workspace: prod